bachelor/urls.py
from django.urls import path, include
from .views import b_application_view, load_cities, abitur_page, PdfDetail, list_b_view
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('add', b_application_view, name='add_bachelor'),
    # path(r'^p/(?P<id>\d+)$', abitur_page, name='abitur_detail'),
    path('', list_b_view, name='list_b'),
    # path('list/<int:id>', abitur_page, name='abitur_view'),
    # path('search/', search, name='search'),
    path('<int:pk>', PdfDetail.as_view(), name='ruxsatnoma'),
    # path('page_pdf/', page_pdf, name='page_pdf'),
    path('ajax/load-cities/', load_cities, name='ajax_load_cities'),
]

if settings.DEBUG:
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

magistr/urls.py
from django.urls import path, include
from .views import m_application_view, load_cities

urlpatterns = [
    path('add/', m_application_view, name='add_magistr'),
    path('ajax/load-cities/', load_cities, name='ajax_load_cities'),
]

qabul/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from home.views import index_view

app_name='bachelor'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index_view),
    # path('list/', list_app, name='list'),
    # path('upload/', upload, name='upload'),
    path('bachelor/', include('bachelor.urls')),
    path('magistr/', include('magistr.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

bachelor/models.py
from django.db import models
from home.models import TYPE_GENDER, Country, Nationality, Region, Tuman, STATUS
from django.urls import reverse

# Create your models here.

TYPE_INSTITUTION = [
    ('Профессиональный колледж', 'Профессиональный колледж'),
    ('Академический лицей', 'Академический лицей'),
    ('Школа', 'Школа'),
]

class Branch(models.Model):
    parent = models.ForeignKey('self', blank=True, null=True, related_name='children', on_delete=models.CASCADE)

    branch_name = models.CharField(max_length=499, null=True)

    def __str__(self):
        return f"{self.branch_name}"


class Application(models.Model):
    branch_name = models.ForeignKey(Branch, on_delete=models.CASCADE, null=True, verbose_name='Выберите специальность')

    last_name = models.CharField(max_length=50, null=True, verbose_name='Фамилия')
    first_name = models.CharField(max_length=50, null=True, verbose_name='Имя')
    sure_name = models.CharField(max_length=50, null=True, verbose_name= 'Отчество')
    date_of_birth = models.DateField(null=True, verbose_name='Дата рождения')
    gender = models.CharField(max_length=20, choices=TYPE_GENDER, verbose_name='Выберите пол', null=True)
    photo = models.ImageField(upload_to='photo/', null=True, verbose_name='Фотография 3х4 (jpg, jpeg, png)')
    ####
    country = models.ForeignKey(Country, on_delete=models.CASCADE, null=True, verbose_name='Гражданство')
    nationality = models.ForeignKey(Nationality, on_delete=models.CASCADE, null=True, verbose_name='Национальность', blank=True)
    region = models.ForeignKey(Region, on_delete=models.SET_NULL, null=True, verbose_name='Область')
    tuman = models.ForeignKey(Tuman, on_delete=models.SET_NULL, null=True, verbose_name='Район')
    adress = models.CharField(max_length=499, null=True, verbose_name='Улица, дом, квартира')
    pasport = models.CharField(max_length=9, null=True, unique=True, verbose_name='Серия и номер паспорта')
    pasport_image = models.ImageField(upload_to='pasport/', null=True, verbose_name='Электронный образ паспорта')
    ####
    type_institution = models.CharField(choices=TYPE_INSTITUTION, max_length=60, null=True, verbose_name='Тип заведения')
    name_institution = models.CharField(max_length=299, null=True, verbose_name='Название учреждения')
    year = models.CharField(max_length=4, null=True, verbose_name='Год выпуска')
    diplom = models.CharField(max_length=10, null=True, verbose_name='Серия и номер диплома или аттестата')
    diplom_photo = models.FileField(upload_to='diplom/', null=True, verbose_name='Электронный образ диплома или аттестата')
    ielts = models.FileField(upload_to='ielts/', null=True, verbose_name='Сертификат о знании иностранного языка', help_text='IELTS Если если имеется', blank=True)
    phone = models.CharField(max_length=12, unique=True, null=True)
    create_at = models.DateTimeField(auto_now_add=True, null=True)
    update_at = models.DateTimeField(auto_now=True, null=True)

    status = models.CharField(max_length=50, choices=STATUS, default='New', blank=True, null=True, verbose_name='Статус')

    def __str__(self):
        return f"{self.last_name}|{self.first_name}|{self.branch_name}==>{self.status}"

    def get_absolute_url(self):
        return reverse('abitur_view', args=[self.id,])

    # def get_absolute_url(self):
    #     return "/app/%s/" %(self.id)

home/models.py
from django.db import models
from django.forms import ModelForm, Select, TextInput, FileInput
from django import forms

# Create your models here.

TYPE_GENDER = [
        ('Мужчина', 'Эркак'),
        ('Женщина', 'Аёл'),
    ]

STATUS = [
        ('New', 'Yangi'),
        ('Under consideration', 'Ko\'rib chiqilmoqda'),
        ('Accepted', 'Qabul qilindi'),
        ('Rejection', 'Qaytarildi'),
    ]



class Country(models.Model):
    name = models.CharField(max_length=200, null=True, unique=True)

    def __str__(self):
        return f"{self.name}"

class Region(models.Model):
    # country = models.ForeignKey(Country, on_delete=models.CASCADE, null=True,)
    name = models.CharField(max_length=200, null=True, unique=True)

    def __str__(self):
        return f"{self.name}"

class Tuman(models.Model):
    region = models.ForeignKey(Region, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200, null=True, unique=True)

    def __str__(self):
        return f"{self.name}"

class Nationality(models.Model):
    nationality = models.CharField(max_length=100, null=True)

    def __str__(self):
        return f"{self.nationality}"

bachelor/forms.py
from .models import Application, Region, Tuman, Country
from django import forms
from django.forms import ModelForm, TextInput, Form, Select, FileInput, DateInput


class ApplicationForm(ModelForm):
    class Meta:
        model = Application
        fields = ['branch_name', 'last_name', 'first_name', 'sure_name', 'date_of_birth', 'gender', 'nationality', 'photo',
                  'country', 'region', 'tuman', 'adress', 'pasport', 'pasport_image',
                  'type_institution', 'name_institution', 'year', 'diplom', 'diplom_photo', 'ielts', 'phone',]
        widgets = {
            # 'branch_name' : Select(attrs={'class':'input'}),
            # 'last_name' : TextInput(attrs={'class':'input2',}),
            # 'sure_name': TextInput(attrs={'class':'input2'}),
            # 'first_name': TextInput(attrs={'class':'input2'}),
            'date_of_birth': DateInput(attrs={'type':'date'}),
            # 'gender': Select(attrs={'class': 'input'}),
            # 'nationality': Select(attrs={'class':'input'}),
            # 'photo': FileInput(attrs={'class':'file-upload'}),
            # 'country': Select(attrs={'class':'input'}),
            # 'region': Select(attrs={'class':'input'}),
            # 'tuman': Select(attrs={'class':'input'}),
            # 'adress': TextInput(attrs={'class':'input'}),
            # 'pasport': TextInput(attrs={'class':'input'}),
            # 'pasport_image': FileInput(attrs={'class':'file-upload'}),
            # 'type_institution': Select(attrs={'class':'input'}),
            # 'name_institution': TextInput(attrs={'class':'input'}),
            # 'year': TextInput(attrs={'class':'input'}),
            # 'diplom': TextInput(attrs={'class':'input'}),
            # 'diplom_photo': FileInput(attrs={'class':'file-upload'}),
            # 'ielts': FileInput(attrs={'class':'file-upload'}),
            # 'phone': TextInput(attrs={'class':'input'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['tuman'].queryset = Tuman.objects.none()

        if 'region' in self.data:
            try:
                region_id = int(self.data.get('region'))
                self.fields['tuman'].queryset = Tuman.objects.filter(region_id=region_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['tuman'].queryset = self.instance.region.tuman_set.order_by('name')


class SearchForm(forms.Form):
    query = forms.CharField(max_length=100)
    catid = forms.IntegerField()

home/forms.py
from django import forms

magistr/forms.py
from django.forms import ModelForm, DateInput, Select
from .models import Magapplication, Branch
from home.models import Region, Tuman

class Magapplicationform(ModelForm):
    class Meta:
        model = Magapplication
        fields = ['branch_name', 'last_name', 'first_name', 'sure_name', 'date_of_birth', 'gender', 'nationality',
                  'photo','country', 'region', 'tuman', 'adress', 'pasport', 'pasport_image',
                  'name_institution', 'year', 'diplom', 'diplom_photo', 'ielts', 'phone', ]
        widgets = {
            'date_of_birth': DateInput(attrs={'type': 'date'}),
            # 'region': Select(attrs={'class': 'input'}),
            # 'tuman': Select(attrs={'class': 'input'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['tuman'].queryset = Tuman.objects.none()

        if 'region' in self.data:
            try:
                region_id = int(self.data.get('region'))
                self.fields['tuman'].queryset = Tuman.objects.filter(region_id=region_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['tuman'].queryset = self.instance.region.tuman_set.order_by('name')

bachelor/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Application, Branch
from .forms import ApplicationForm, SearchForm
from django.contrib import messages
from home.models import Region, Tuman
from django.http import HttpResponse, HttpResponseRedirect
from easy_pdf.views import PDFTemplateView, PDFTemplateResponseMixin
from django.views.generic import DetailView, TemplateView

from django.http import FileResponse
import io
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import letter

# Create your views here.
def b_application_view(request):
    # form = ApplicationForm()
    if request.method == "POST":
        form = ApplicationForm(request.POST, request.FILES)
        if form.is_valid():
            print(request.POST)
            form.save()
            # data = Application()
            # data.branch_name = form.cleaned_data['branch_name']
            # data.last_name = form.cleaned_data['last_name']
            # data.first_name = form.cleaned_data['first_name']
            # data.sure_name = form.cleaned_data['sure_name']
            # data.date_of_birth = form.cleaned_data['date_of_birth']
            # data.gender = form.cleaned_data['gender']
            # data.nationality = form.cleaned_data['nationality']
            # data.photo = form.cleaned_data['photo']
            # data.country = form.cleaned_data['country']
            # data.region = form.cleaned_data['region']
            # data.tuman = form.cleaned_data['tuman']
            # data.adress = form.cleaned_data['adress']
            # data.pasport = form.cleaned_data['pasport']
            # data.pasport_image = form.cleaned_data['pasport_image']
            # data.type_institution = form.cleaned_data['type_institution']
            # data.name_institution = form.cleaned_data['name_institution']
            # data.year = form.cleaned_data['year']
            # data.diplom = form.cleaned_data['diplom']
            # data.diplom_photo = form.cleaned_data['diplom_photo']
            # data.ielts = form.cleaned_data['ielts']
            # data.phone = form.cleaned_data['phone']
            # data.save()
            messages.success(request, 'OK!!!')
        else:
            messages.success(request, 'NONONONON')
        return redirect('add_bachelor')

    form = ApplicationForm()
    # branch = Branch.objects.all()
    context = {
        'form': form,
    }
    return render(request, 'bachelor.html', context)

######

def list_b_view(request):
    search_query = request.GET.get('search','')
    if search_query:
       app = Application.objects.filter(pasport__icontains=search_query)
    else:
        app = Application.objects.all()
    return render(request, 'list_b.html', {'app':app})


def abitur_page(request, id):
    app = get_object_or_404(Application, pk=id)
    # my = Application.objects.get(pk=id)
    return render(request, 'abitur_page.html', {'app': app})


class PdfDetail(PDFTemplateResponseMixin, DetailView):
    template_name = 'pdf_detail.html'
    context_object_name = 'app'
    model = Application
    # encoding = u"utf-8"




def load_cities(request):
    region_id = request.GET.get('region_id')
    tumans = Tuman.objects.filter(region_id=region_id).all()
    return render(request, 'city_dropdown_list_options.html', {'tumans': tumans})
    # return JsonResponse(list(cities.values('id', 'name')), safe=False)


# def search(request):
#     if request.method == 'POST':
#         form = SearchForm(request.POST)
#         if form.is_valid():
#             query = form.cleaned_data['query']
#             catid = form.cleaned_data['catid']
#             if catid == 0:
#                 apps = Application.objects.filter(pasport__icontains=query)
#             else:
#                 apps = Application.objects.filter(pasport__icontains=query, branch_name_id=catid)
#             barnch = Branch.objects.all()
#             context = {
#                     'apps': apps,
#                     'query': query,
#                     'branch': barnch,
#             }
#             return render(request, 'search.html', context)
#     return render(request, 'list_b.html')

home/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy
from django.shortcuts import render, redirect, get_object_or_404
from home.models import Country, Region, Tuman
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib import messages
import json
from bachelor.models import Application
from magistr.models import Magapplication


# Create your views here.

def index_view(request):
    return render(request, 'index.html')

#####

# def list_app(request):
#     bapps = Application.objects.all()
#     mapps = Magapplication.objects.all()
#
#     return render(request, 'list_b.html', {'bapps':bapps, 'mapps': mapps})



# def upload(request):
#     if request.method == 'POST':
#         uploaded_file = request.FILES['document']
#         print(uploaded_file.name)
#         print(uploaded_file.size)
#     return render(request, 'upload.html')

magistr/views.py
from django.shortcuts import render, redirect
from .models import Magapplication, Branch
from .forms import Magapplicationform
from django.contrib import messages
from home.models import Region, Tuman
from .models import Magapplication
from .forms import Magapplicationform

# Create your views here.

def m_application_view(request):
    if request.method == "POST":
        form = Magapplicationform(request.POST, request.FILES)
        if form.is_valid():
            print(request.POST)
            form.save()
            # data = Magapplication
            # data.branch_name = form.cleaned_data['branch_name']
            # data.last_name = form.cleaned_data['last_name']
            # data.first_name = form.cleaned_data['first_name']
            # data.sure_name = form.cleaned_data['sure_name']
            # data.date_of_birth = form.cleaned_data['date_of_birth']
            # data.gender = form.cleaned_data['gender']
            # data.nationality = form.cleaned_data['nationality']
            # data.photo = form.cleaned_data['photo']
            # data.country = form.cleaned_data['country']
            # data.region = form.cleaned_data['region']
            # data.tuman = form.cleaned_data['tuman']
            # data.adress = form.cleaned_data['adress']
            # data.pasport = form.cleaned_data['pasport']
            # data.pasport_image = form.cleaned_data['pasport_image']
            # data.name_institution = form.cleaned_data['name_institution']
            # data.year = form.cleaned_data['year']
            # data.diplom = form.cleaned_data['diplom']
            # data.diplom_photo = form.cleaned_data['diplom_photo']
            # data.ielts = form.cleaned_data['ielts']
            # data.phone = form.cleaned_data['phone']
            # data.save()
            messages.success(request, 'OK!!!')
        else:
            messages.success(request, 'NONONONONONONO!!!')
        return redirect('add_magistr')
    form = Magapplicationform()
    context = {
        'form': form
    }
    return render(request, 'magistr.html', context)


def load_cities(request):
    region_id = request.GET.get('region_id')
    tumans = Tuman.objects.filter(region_id=region_id).all()
    return render(request, 'city_dropdown_list_options.html', {'tumans': tumans})
    # return JsonResponse(list(cities.values('id', 'name')), safe=False)

home/templates/abitur_page.html
{% extends 'homebase.html' %}
{% load static %}
{#{% block title %}My Home Page{% endblock %}#}
{#{% block keywords %}My Home Keywords{% endblock %}#}
{#{% block description %}My Home Description{% endblock %}#}



{% load static %}
{% block body %}

<title>RUXSTNOMA</title>


    <div class="container">
        <div class="section">
            <h2>DTM</h2>
            <h2>{{ app.last_name}}</h2>
            <h2>{{ app.first_name }}</h2>
            <h2>{{ app.sure_name }}</h2>
        </div>
    </div>
{% endblock %}

home/templates/bachelor.html
{% extends 'homebase.html' %}
{% load static %}
{% block title %}My Home Page{% endblock %}
{% block keywords %}My Home Keywords{% endblock %}
{% block description %}My Home Description{% endblock %}

{% block sidebar %}{% include 'sidebar.html' %} {% endblock %}
{% load static %}
{% load crispy_forms_tags %}

{% block body %}
<div class="section section-grey">

</div>
	<div class="section">
		<!-- container -->
		<div class="container">
            <div class="row">
                <div class="col-md-3">
                    <div class="section-title">
                        <h2>Ariza yuborish</h2>
                    </div>
                    <div class="text-center">
                        <h3> 2021 yil uchun </h3>
                    </div>

                        <form action="{% url 'list_b' %}">
							<input name="search" class="input search-input" type="text" placeholder="Enter your keyword">
							<button class="search-btn" type="submit"><i class="fa fa-search"></i></button>
						</form>

                </div>

                <div class="col-md-9">
                <div class="section-title">
                    <h1>Salom</h1>
                </div>
                    <form method="post" enctype="multipart/form-data" class="clearfix" id = 'personForm' data-cities-url="{% url 'ajax_load_cities' %}">
                        {% csrf_token %}
                            <div class="">
                                 <h3 class="title">{{ setting.title|safe }}</h3>
                             {% if messages %}
                                 {% for message in messages %}
                                    <div class="alert alert-{{ message.tags }}" role="alert">
                                        {{ message }}
                                    </div>
                                 {% endfor %}
                             {% endif %}
                             </div>
                                {% csrf_token %}
                            <div class="">
                                <h3 class="title">{{ setting.title|safe }}</h3>
                             {% if messages %}
                                 {% for message in messages %}
                                    <div class="alert alert-{{ message.tags }}" role="alert">
                                        {{ message }}
                                    </div>
                                 {% endfor %}
                             {% endif %}
                            </div>

                            <div class="row">
                                  <div class="form-group col-md-12 mb-0">
                                    {{ form.branch_name|as_crispy_field }}
                                  </div>
                                  <div class="form-group col-md-4 mb-0">
                                    {{ form.last_name|as_crispy_field }}
                                  </div>
                                  <div class="form-group col-md-4 mb-0">
                                    {{ form.first_name|as_crispy_field }}
                                  </div>
                                  <div class="form-group col-md-4 mb-0">
                                    {{ form.sure_name|as_crispy_field }}
                                  </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-md-4 mb-0">
                                    {{ form.date_of_birth|as_crispy_field }}
                                </div>
                                <div class="form-group col-md-4 mb-0">
                                    {{ form.gender|as_crispy_field }}
                                </div>
                                <div class="form-group col-md-4 mb-0">
                                    {{ form.nationality|as_crispy_field }}
                                </div>
                                <div class="form-group col-md-4 mb-0">
                                    {{ form.photo|as_crispy_field }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4">
                                    {{ form.country|as_crispy_field }}
                                </div>
                                <div class="col-md-4">
                                    {{ form.region|as_crispy_field }}
                                </div>
                                <div class="col-md-4">
                                    {{ form.tuman|as_crispy_field }}
                                </div>
                                <div class="col-md-12">
                                    {{ form.adress|as_crispy_field }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4">
                                    {{ form.pasport|as_crispy_field }}
                                </div>
                                <div class="col-md-4">
                                    {{ form.pasport_image|as_crispy_field }}
                                </div>
                                <div class="col-md-4">
                                    {{ form.type_institution|as_crispy_field }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-8">
                                    {{ form.name_institution|as_crispy_field }}
                                </div>
                                <div class="col-md-4">
                                    {{ form.year|as_crispy_field }}
                                </div>
                                <div class="col-md-4">
                                    {{ form.diplom|as_crispy_field }}
                                </div>
                                <div class="col-md-4">
                                    {{ form.diplom_photo|as_crispy_field }}
                                </div>
                                <div class="col-md-4">
                                    {{ form.ielts|as_crispy_field }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-5">
                                    {{ form.phone|as_crispy_field }}
                                </div>
                            </div>
                            <input type="submit">
                    </form>
                </div>
            </div>
		</div>
	</div>

        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
        <script>
            $("#id_region").change(function () {
                const url = $("#personForm").attr("data-cities-url");  // get the url of the `load_cities` view
                const regionId = $(this).val();  // get the selected country ID from the HTML input

                $.ajax({                       // initialize an AJAX request
                    url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
                    data: {
                        'region_id': regionId       // add the country id to the GET parameters
                    },
                    success: function (data) {   // `data` is the return of the `load_cities` view function
                        $("#id_tuman").html(data);  // replace the contents of the city input with the data that came from the server
                        /*
                        let html_data = '<option value="">---------</option>';
                        data.forEach(function (city) {
                            html_data += `<option value="${city.id}">${city.name}</option>`
                        });
                        console.log(html_data);
                        $("#id_city").html(html_data);
                        */
                    }
                });

            });
        </script>


{% endblock %}
{% block footer %} {% include 'footer.html' %}{% endblock %}

home/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
{% load static %}
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}" />
    <link type="text/css" rel="stylesheet" href="{% static 'css/slick.css'%}" />
	<link type="text/css" rel="stylesheet" href="{% static 'css/slick-theme.css'%}" />
    <link type="text/css" rel="stylesheet" href="{% static 'css/nouislider.min.css'%}" />
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}" />
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>

    <title>{{ title|default:"" }}</title>

    {% block style_base %}
        {% comment %}
            See DEFAULT_CSS in https://github.com/chrisglass/xhtml2pdf/blob/master/xhtml2pdf/default.py
            for base style.
        {% endcomment %}

        {% block layout_style %}
            <style type="text/css">
                {#@font-face { font-family: Arial; src: url("/home/static/fonts/arial.ttf"); }#}
                @page {
                    size: {{ pagesize|default:"A4" }};
                    margin-left: 2cm;
                    margin-right: 2cm;
                    margin-top: 1cm;
                    margin-bottom: 2cm;

                    @frame header {
                        -pdf-frame-content: page-header;
                        margin-top: 0.7cm;
                        margin-right: 2mm;
                        margin-bottom: 0cm;
                        margin-left: 1.2cm;
                    }

                    @frame footer {
                        -pdf-frame-content: page-footer;
                        bottom: 0cm;
                        margin-left: 1cm;
                        margin-right: 1cm;
                        height: 1cm;
                    }


            </style>
        {%endblock%}
        {% block extra_style %}
{#            <meta http-equiv="content-type" content="text/html; charset=utf-8">#}
        {% endblock %}
    {% endblock %}
</head>
<body>

    <div>
        {%block page_header%}
        {%endblock%}

        {%block content%}
        {%endblock%}
    </div>

    <div id="page-footer">
        {%block page_foot%}
            {% comment %}
                <pdf:pagenumber />
            {% endcomment %}
        {%endblock%}
    </div>
</body>
</html>

home/templates/city_dropdown_list_options.html
<option value="">---------</option>
{% for tuman in tumans %}
<option value="{{ tuman.pk }}">{{ tuman.name }}</option>
{% endfor %}

home/templates/header.html
{% load static %}
<header>
		<!-- top Header -->
		<div id="top-header">
			<div class="container">
				<div class="pull-left">
					<span>Tashkent State Agrarian University </span>
				</div>

			</div>
		</div>
		<!-- /top Header -->

		<!-- header -->
		<div id="header">
			<div class="container">
				<div class="pull-left">
					<!-- Logo -->
					<div class="header-logo">
						<a class="logo" href="/">
							<img src="{% static 'img/logo-uz.png'%}" alt="">
						</a>
					</div>
					<!-- /Logo -->

                        <li class="nav-toggle">
							<button class="nav-toggle-btn main-btn icon-btn"><i class="fa fa-bars"></i></button>
                        </li>
						    <!-- / Mobile nav toggle -->


                </div>

			</div>
			<!-- header -->
		</div>
		<!-- container -->
	</header>

home/templates/list_b.html
{% extends 'homebase.html' %}
{% load static %}
{% block title %}My Home Page{% endblock %}
{% block keywords %}My Home Keywords{% endblock %}
{% block description %}My Home Description{% endblock %}

{% block sidebar %}{% include 'sidebar.html' %} {% endblock %}

{% load crispy_forms_tags %}
{% block body %}
    <div class="container">
        <div class="section">
        <h1 class="section-title">Application</h1>
        {% for a in app  %}
            <a href="{{ a.id }}"><h1>{{ a.last_name }}</h1></a>
{#            <a href = {{ a.get_absolute_url }}><h3>{{ a.last_name }}</h3></a>#}
{#            <a href="{% url 'page_pdf' %}">PDF_PAGE</a>#}
        {% endfor %}
        </div>
    </div>
{% endblock %}
{% block footer %} {% include 'footer.html' %}{% endblock %}

home/templates/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Upload</title>
</head>
<body>
<h1>Upload</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="document">
        <button type="submit">Upload</button>
    </form>
</body>
</html>